[build]
  base = "dasbor-asisten"
  command = "npm run build"
  publish = "dist"
  functions = "dasbor-asisten/netlify/function" # <-- INI YANG BENAR

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200